-- MySQL Script generated by MySQL Workbench
-- Sun 16 Sep 2018 07:31:11 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dcart_flic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dcart_flic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dcart_flic` DEFAULT CHARACTER SET utf8 ;
USE `dcart_flic` ;

-- -----------------------------------------------------
-- Table `dcart_flic`.`dcart_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcart_flic`.`dcart_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `store_url` VARCHAR(150) NOT NULL,
  `public_key` VARCHAR(250) NOT NULL,
  `token` VARCHAR(250) NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `entered` DATETIME NOT NULL,
  `modified` DATETIME NULL,
  `enabled` TINYINT(1) NOT NULL,
  UNIQUE INDEX `store_url_UNIQUE` (`store_url` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
